# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/eren/Desktop/ws2022-group-10-belle-minimum-spanning-tree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/eren/Desktop/ws2022-group-10-belle-minimum-spanning-tree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eren/Desktop/ws2022-group-10-belle-minimum-spanning-tree/CMakeFiles /Users/eren/Desktop/ws2022-group-10-belle-minimum-spanning-tree//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eren/Desktop/ws2022-group-10-belle-minimum-spanning-tree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flow

# Build rule for target.
flow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flow
.PHONY : flow

# fast build rule for target.
flow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/build
.PHONY : flow/fast

src/OpticalFlow.o: src/OpticalFlow.cpp.o
.PHONY : src/OpticalFlow.o

# target to build an object file
src/OpticalFlow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/OpticalFlow.cpp.o
.PHONY : src/OpticalFlow.cpp.o

src/OpticalFlow.i: src/OpticalFlow.cpp.i
.PHONY : src/OpticalFlow.i

# target to preprocess a source file
src/OpticalFlow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/OpticalFlow.cpp.i
.PHONY : src/OpticalFlow.cpp.i

src/OpticalFlow.s: src/OpticalFlow.cpp.s
.PHONY : src/OpticalFlow.s

# target to generate assembly for a file
src/OpticalFlow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/OpticalFlow.cpp.s
.PHONY : src/OpticalFlow.cpp.s

src/mg.o: src/mg.cpp.o
.PHONY : src/mg.o

# target to build an object file
src/mg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/mg.cpp.o
.PHONY : src/mg.cpp.o

src/mg.i: src/mg.cpp.i
.PHONY : src/mg.i

# target to preprocess a source file
src/mg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/mg.cpp.i
.PHONY : src/mg.cpp.i

src/mg.s: src/mg.cpp.s
.PHONY : src/mg.s

# target to generate assembly for a file
src/mg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flow.dir/build.make CMakeFiles/flow.dir/src/mg.cpp.s
.PHONY : src/mg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flow"
	@echo "... src/OpticalFlow.o"
	@echo "... src/OpticalFlow.i"
	@echo "... src/OpticalFlow.s"
	@echo "... src/mg.o"
	@echo "... src/mg.i"
	@echo "... src/mg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

